win_pulse and win_sample scheduling
ISI-apex/halide-sar-app pull request #21
Opened 2021-02-18 13:59 UTC by Infinoid

Turns `taylor()` into a `Taylor` class that holds the inner Funcs for later scheduling.
Add scheduling directives based on the autoscheduler.

Before (Sandia dataset, CUDA, single node):
```
Halide backprojection start 
Halide backprojection returned 0 in 4558 ms
Halide dB conversion start
Halide dB conversion returned 0 in 14 ms
Halide PNG production start
Halide PNG production returned 0 in 6 ms
Wrote Sandia-cuda.png in 173 ms
backprojection_cuda
 total time: 4557.712402 ms  samples: 4302  runs: 1  time/run: 4557.712402 ms
 average threads used: 3.274291
 heap allocations: 986  peak heap usage: 262012928 bytes
  overhead:              88.010ms  (1%)    threads: 0.000 
  norm_r0:               0.000ms   (0%)    threads: 0.000 
  filt:                  0.000ms   (0%)    threads: 0.000  peak: 7200     num: 1         avg: 7200
  win_pulse:             0.000ms   (0%)    threads: 0.000  peak: 15992    num: 1         avg: 15992
  win_pulse_maximum:     1.057ms   (0%)    threads: 20.000 stack: 32
  win_pulse_w:           169.501ms (3%)    threads: 25.031 peak: 1791104  num: 512       avg: 63968 stack: 32
  win_pulse_F_m_num:     1.057ms   (0%)    threads: 24.000 stack: 32
  win_pulse_F_m_den:     15.909ms  (0%)    threads: 21.133 stack: 32
  win_sample:            0.000ms   (0%)    threads: 0.000  peak: 14400    num: 1         avg: 14400
  win_sample_maximum:    2.114ms   (0%)    threads: 19.000 stack: 32
  win_sample_w:          144.236ms (3%)    threads: 23.352 peak: 1670400  num: 464       avg: 57600 stack: 32
  win_sample_F_m_num:    1.063ms   (0%)    threads: 29.000 stack: 32
  win_sample_F_m_den:    25.411ms  (0%)    threads: 15.833 stack: 32
  win:                   8.460ms   (0%)    threads: 1.000  peak: 28785600 num: 1         avg: 28785600
  phs_filt:              19.057ms  (0%)    threads: 1.000  peak: 57571200 num: 1         avg: 57571200
  phs_pad:               13.790ms  (0%)    threads: 15.750 peak: 131006464 num: 1        avg: 131006464
  fftshift:              19.363ms  (0%)    threads: 24.777 peak: 131006464 num: 1        avg: 131006464
  dft:                   26.679ms  (0%)    threads: 36.680 peak: 131006464 num: 1        avg: 131006464
  Q:                     24.392ms  (0%)    threads: 32.434 peak: 131006464 num: 1        avg: 131006464
  fimg:                  33.884ms  (0%)    threads: 1.000  peak: 67108864 num: 1         avg: 67108864
  norm_rr0:              0.000ms   (0%)    threads: 0.000  stack: 8
  output_img:            3963.722ms(86%)   threads: 1.015 
```

After:
```
Halide backprojection start 
Halide backprojection returned 0 in 4243 ms
Halide dB conversion start
Halide dB conversion returned 0 in 15 ms
Halide PNG production start
Halide PNG production returned 0 in 6 ms
Wrote Sandia-cuda.png in 170 ms
backprojection_cuda
 total time: 4242.067871 ms  samples: 3974  runs: 1  time/run: 4242.067871 ms
 average threads used: 1.455209
 heap allocations: 12  peak heap usage: 262012928 bytes
  overhead:              88.760ms  (2%)    threads: 0.000 
  norm_r0:               0.000ms   (0%)    threads: 0.000 
  filt:                  0.000ms   (0%)    threads: 0.000  peak: 7200     num: 1         avg: 7200
  win_pulse_w:           3.182ms   (0%)    threads: 0.333  peak: 15992    num: 1         avg: 15992
  win_pulse_F_m_num:     0.000ms   (0%)    threads: 0.000  stack: 32
  win_pulse_F_m_den:     0.000ms   (0%)    threads: 0.000  stack: 32
  win_pulse:             0.000ms   (0%)    threads: 0.000  peak: 15992    num: 1         avg: 15992
  win_pulse_maximum:     1.059ms   (0%)    threads: 4.000  stack: 32
  win_sample_w:          3.171ms   (0%)    threads: 0.000  peak: 14400    num: 1         avg: 14400
  win_sample_F_m_num:    0.000ms   (0%)    threads: 0.000  stack: 32
  win_sample_F_m_den:    0.000ms   (0%)    threads: 0.000  stack: 32
  win_sample:            1.059ms   (0%)    threads: 0.000  peak: 14400    num: 1         avg: 14400
  win_sample_maximum:    0.000ms   (0%)    threads: 0.000  stack: 32
  win:                   10.589ms  (0%)    threads: 1.000  peak: 28785600 num: 1         avg: 28785600
  phs_filt:              25.381ms  (0%)    threads: 1.000  peak: 57571200 num: 1         avg: 57571200
  phs_pad:               16.248ms  (0%)    threads: 10.888 peak: 131006464 num: 1        avg: 131006464
  fftshift:              21.849ms  (0%)    threads: 11.066 peak: 131006464 num: 1        avg: 131006464
  dft:                   30.077ms  (0%)    threads: 32.428 peak: 131006464 num: 1        avg: 131006464
  Q:                     25.496ms  (0%)    threads: 31.250 peak: 131006464 num: 1        avg: 131006464
  fimg:                  41.416ms  (0%)    threads: 1.000  peak: 67108864 num: 1         avg: 67108864
  norm_rr0:              0.000ms   (0%)    threads: 0.000  stack: 8
  output_img:            3973.775ms(93%)   threads: 1.013 
```

2021-02-18 14:10 UTC, cimes-isi commented
Thanks. Gonna keep this on the back burner for now, probably until after our demo next week.

I think the only time we'll really see benefit from optimizing these taylor functions is close to maximum distributed scale, when the output image is sliced up small enough that the later stages have relatively little work to do (the overhead of these earlier stages thus become a more significant portion of total backprojection runtime).  Even in such cases, it's a reasonable question to ask if we've simply scaled out too far for a fixed data size.

2021-02-18 14:14 UTC, Infinoid commented
If this overhead matters less as the problem size increases, then that makes sense.  You're using some huge datasets.

2021-03-29 14:26 UTC, cimes-isi commented
I think we can probably move forward with getting some version of this PR merged, but some changes are needed first.  At a minimum, we need to resolve conflicts, and there are several code comments that I'll make as well.

I'm still iffy about introducing a custom class into the backprojection pipeline.  It seems to taint an otherwise pure Halide pipeline.  I wish Halide had its own native way to encapsulate several Funcs to form complex, library-like functions while still supporting fine-grained scheduling for the inner Funcs.  The most general way I can think of doing this right now is for `taylor` to be a `std::vector<Func>`, or even a `std::map<std:string, Func>` to access internal Funcs by name during scheduling, rather than a custom class.  I've prototyped both these approaches, but am not sure they provide any real benefit over a custom class.  Maybe we're unaware of some more advanced Halide functionality, e.g., that the autoschedulers could handle more cleanly as well (without having to "get" inner Funcs by index)?

2021-03-29 14:29 UTC, cimes-isi requested changes

2021-03-29 14:29 UTC, cimes-isi commented on backprojection.cpp
> +                      .parallel(sample_vo);
pedantic: fix indenting here and elsewhere to align with the `compute_root` call.

2021-03-29 14:29 UTC, cimes-isi commented on backprojection.cpp
> +                      .split(sample, sample_vo, sample_vi, 4)
Use `vectorsize` rather than hardcoded value of 4, here and elsewhere.

2021-03-29 14:29 UTC, cimes-isi commented on backprojection.cpp
> +    Taylor win_sample, win_pulse;
pedantic: let's keep these declared on separate lines, as we did before.

2021-03-31 18:32 UTC, Infinoid commented
This change is a month and a half old, and I barely remember it.  But I attempted to resolve conflicts and apply your suggestions.

2021-03-31 18:53 UTC, merged